test_cases:
- description: ''
  name: 获取用户列表
  request:
    body: null
    headers:
      Content-Type: application/json
    method: GET
    path: /api/users
    path_params: []
    query_params: []
  response:
    expected_status_codes:
    - '200'
    responses:
      '200':
        content: null
        description: 成功响应
  tags: []
- description: ''
  name: 创建用户
  request:
    body:
      content_type: application/json
      schema:
        properties:
          email:
            type: string
          name:
            type: string
        type: object
    headers:
      Content-Type: application/json
    method: POST
    path: /api/users
    path_params: []
    query_params: []
  response:
    expected_status_codes:
    - '201'
    responses:
      '201':
        content: null
        description: 创建成功
  tags: []
- description: ''
  name: 获取用户详情
  request:
    body: null
    headers:
      Content-Type: application/json
    method: GET
    path: /api/users/{id}
    path_params:
    - description: ''
      name: id
      required: true
      type: integer
    query_params: []
  response:
    expected_status_codes:
    - '200'
    responses:
      '200':
        content: null
        description: 成功响应
  tags: []
total_count: 3
